//MUTATIONS
export const MUTATE_CURRENT_PAGE = 'MUTATE_CURRENT_PAGE';
export const MUTATE_ORIENTATION = 'MUTATE_ORIENTATION';
export const MUTATE_LOADING = 'MUTATE_LOADING';
export const MUTATE_INVOICE_HISTORY = 'MUTATE_INVOICE_HISTORY';
export const MUTATE_SETTINGS_FIRST_STEP = 'MUTATE_SETTINGS_FIRST_STEP';

//ACTIONS
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_ORIENTATION = 'SET_ORIENTATION';
export const LOAD_INVOICE_HISTORY = 'LOAD_INVOICE_HISTORY';
export const LOAD_SETTINGS_FIRST_STEP = 'LOAD_SETTINGS_FIRST_STEP';

//GETTERS
export const GET_CURRENT_PAGE = 'GET_CURRENT_PAGE';
export const GET_ORIENTATION = 'GET_ORIENTATION';
export const GET_LOADING = 'GET_LOADING';
export const GET_INVOICE_HISTORY = 'GET_INVOICE_HISTORY';
export const GET_SETTINGS_FIRST_STEP_DATA = 'GET_SETTINGS_FIRST_STEP_DATA';
export const GET_SETTINGS_FIRST_STEP_STATIC_DATA = 'GET_SETTINGS_FIRST_STEP_STATIC_DATA';